# dot-cli.yml
name: 'dot-cli'
description: 'Fire dotCMS cli'
inputs:
  command: 
    description: 'dot-cli command'
    required: true
    default: 'push'
  directory: 
    description: 'what we want to push'  
    required: true
    default: '.'
  
outputs:
  return-code: # id of output.
    description: 'Command return code'
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.directory }}  