# dot-cli.yml
name: 'dot-cli'
description: 'Fire dotCMS cli'
inputs:
  token:
    description: 'dotCMS token'
    required: true    
  command: 
    description: 'dot-cli command'
    required: true
    default: 'push'
  sub-command: 
    description: 'sub-command'
    required: false    
  default-action-arg:     
    required: false      
  option:     
    required: false
  option-value:     
    required: false        
    
  
outputs:
  return-code: # id of output.
    description: 'Command return code'
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:  # 'ct pull FileAsset --workspace /github/workspace/'
    - ${{ inputs.token }}
    - ${{ inputs.command }}
    - ${{ inputs.sub-command }}
    - ${{ inputs.default-action-arg }}
    - ${{ inputs.option }}
    - ${{ inputs.option-value }}