# dot-cli.yml
name: 'dot-cli'
description: 'Fire dotCMS cli'
inputs:
  token:
    description: 'dotCMS token'
    required: true    
  command: 
    description: 'dot-cli command'
    required: true
    default: 'push'
  
outputs:
  return-code: # id of output.
    description: 'Command return code'
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}   
    - ${{ inputs.command }}    