name: GHA Capabilities

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3      
        id: checkout
        with:
           fetch-depth: 0

      - name: Get changes
        id: changed-files
        run: |
          echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT

      - name: List changed files
        run: |
            for file in ${{ steps.changed-files.outputs.changed_files }}; do
                echo "$file was changed"
            done    

      - name: Get Event Context properies
        run: |
            echo "Event: ${{ github.event }}"
            echo "Event Name: ${{ github.event_name }}"
            echo "Repository: ${{ github.repository }}"
            echo "Commit SHA: ${{ github.sha }}"
            echo "Commit Ref: ${{ github.ref }}"
            echo "Head Ref: ${{ github.head_ref }}"
            echo "Base Ref: ${{ github.base_ref }}"
            echo "Triggered by: ${{ github.actor }}"
            echo "Workflow: ${{ github.workflow }}"
            echo "PR: ${{ github.pull_request }}"

      - name: Trigger dot-cli
        uses: ./actions/dot-cli
        id: dot-cli
        with:           
           command: 'ct'
           sub-command: 'pull'
           default-action-arg: 'FileAsset'
           option: '--workspace'
           option-value: '/github/workspace/' 
           option-verbose: '--verbose'     

      - name: Get the cli return-code
        run: echo "The time was ${{ steps.dot-cli.outputs.return-code }}"